### ISSUE TITLE
element.matches not widely supported

### ISSUE THREAD

**Issue by axelboc** [icelab/viewloader#2]
Since commit 08a674a244ef0c59662dc01507d40de01a4c9760, the viewloader throws in many browsers when trying to match an element to the `[data-view-...]` selector.

Support for the `element.matches` method is still quite poor (http://caniuse.com/#feat=matchesselector), so would it be possible to simply check for the presence of the `data-view-...` attribute with `element.hasAttribute()` instead?

**Comment by makenosound** [comment]
@axelboc Yep, happy to have that adjusted to something more inclusive of older browsers. We’ll need to remove the surrounding braces from the passed `selector`, but I think `hasAttribute` would suffice.
